@host = http://localhost:5000

# Register API test
POST {{host}}/auth/register
Content-Type: application/json

{
    "username": "user-test5",
    "email": "email-test5@test.com",
    "password": "pass-test5"
}


###
# Login API test
POST {{host}}/auth/login
Content-Type: application/json

{
    "email": "email-test4@test.com",
    "password": "pass-test4"
}

###
# access private route with token
GET  {{host}}/private
Content-Type: application/json
Authorization: Bearer <enter-you-token-here>