@host = http://localhost:5000

# Register API test
POST {{host}}/auth/register
Content-Type: application/json

{
    "username": "user-test5",
    "email": "email-test5@test.com",
    "password": "pass-test5"
}


###
# Login API test
POST {{host}}/auth/login
Content-Type: application/json

{
    "email": "email-test4@test.com",
    "password": "pass-test4"
}

###
# access private route with token
GET  {{host}}/private
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtYWlsLXRlc3Q0QHRlc3QuY29tIiwiaWF0IjoxNjQwMjY5Mjc3LCJleHAiOjE2NDAyNjk4Nzd9.kN2PZr54t5WTF5MgNkjKoYQ-SVUXFwPOmKKsOS-pgjI